### ISSUE TITLE
Add other popular VPN providers

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/vopono#10]
With Wireguard:
* AzireVPN
* TorGuard

OpenVPN only:
* ProtonVPN
* NordVPN
* ExpressVPN
* AirVPN
* Surfshark
* Cyberghost

**Comment by Urdan** [comment]
Hi. Any idea what this error means please? 

`$ vopono -v exec --custom /etc/openvpn/ovpn_tcp/us6116.nordvpn.com.tcp.ovpn --protocol openvpn "brave"       
 2021-02-05T21:30:11.408Z DEBUG vopono::pulseaudio > Setting PULSE_SERVER to unix:/run/user/1000/pulse/native
 2021-02-05T21:30:11.408Z INFO  vopono::util       > Calling sudo for elevated privileges, current user will be used as default user
 2021-02-05T21:30:11.408Z DEBUG vopono::util       > Args: ["vopono", "-v", "exec", "--custom", "/etc/openvpn/ovpn_tcp/us6116.nordvpn.com.tcp.ovpn", "--protocol", "openvpn", "brave"]
 2021-02-05T21:30:11.563Z DEBUG vopono::pulseaudio > Setting PULSE_SERVER to unix:/run/user/1000/pulse/native
 2021-02-05T21:30:11.565Z DEBUG vopono::util       > Existing namespaces: ["vopono_custom_us61"]
 2021-02-05T21:30:11.565Z DEBUG vopono::util       > Removing dead namespace: vopono_custom_us61
 2021-02-05T21:30:11.565Z DEBUG vopono::util       > ip netns delete vopono_custom_us61
 2021-02-05T21:30:11.571Z DEBUG vopono::network_interface > ip addr
 2021-02-05T21:30:11.576Z DEBUG vopono::exec              > Interface: enp5s0
 2021-02-05T21:30:11.577Z DEBUG vopono::util              > Existing namespaces: []
 2021-02-05T21:30:11.577Z DEBUG vopono::util              > ip netns add vopono_custom_us61
 2021-02-05T21:30:11.580Z INFO  vopono::netns             > Created new network namespace: vopono_custom_us61
 2021-02-05T21:30:11.581Z DEBUG vopono::util              > Existing interfaces: 
 2021-02-05T21:30:11.582Z DEBUG vopono::util              > Assigned IPs: []
 2021-02-05T21:30:11.582Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip addr add 127.0.0.1/8 dev lo
 2021-02-05T21:30:11.585Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip link set lo up
 2021-02-05T21:30:11.587Z DEBUG vopono::veth_pair         > NetworkManager detected, adding custom_us61_d to unmanaged devices
 2021-02-05T21:30:11.587Z DEBUG vopono::util              > nmcli connection reload
 2021-02-05T21:30:11.615Z DEBUG vopono::util              > ip link add custom_us61_d type veth peer name custom_us61_s
 2021-02-05T21:30:11.618Z DEBUG vopono::util              > ip link set custom_us61_d up
 2021-02-05T21:30:11.619Z DEBUG vopono::util              > ip link set custom_us61_s netns vopono_custom_us61 up
 2021-02-05T21:30:11.652Z DEBUG vopono::util              > ip addr add 10.200.1.1/24 dev custom_us61_d
 2021-02-05T21:30:11.657Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip addr add 10.200.1.2/24 dev custom_us61_s
 2021-02-05T21:30:11.661Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip route add default via 10.200.1.1 dev custom_us61_s
 2021-02-05T21:30:11.666Z INFO  vopono::netns             > IP address of namespace as seen from host: 10.200.1.2
 2021-02-05T21:30:11.666Z INFO  vopono::netns             > IP address of host as seen from namespace: 10.200.1.1
 2021-02-05T21:30:11.666Z DEBUG vopono::util              > nft add table inet vopono_nat
 2021-02-05T21:30:11.668Z DEBUG vopono::util              > nft add chain inet vopono_nat postrouting { type nat hook postrouting priority 100 ; }
 2021-02-05T21:30:11.671Z DEBUG vopono::util              > nft add rule inet vopono_nat postrouting oifname enp5s0 ip saddr 10.200.1.0/24 counter masquerade
Error: NAT is only supported for IPv4/IPv6
add rule inet vopono_nat postrouting oifname enp5s0 ip saddr 10.200.1.0/24 counter masquerade
                                                                                   ^^^^^^^^^^
 2021-02-05T21:30:11.675Z DEBUG vopono::util              > ip link delete custom_us61_d
 2021-02-05T21:30:11.708Z DEBUG vopono::util              > nmcli general reload
Error: argument 'reload' not understood. Try passing --help instead.
thread 'main' panicked at 'Failed to reload NetworkManager configuration: Command failed: nmcli general reload', src/veth_pair.rs:127:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by jamesmcm** [comment]
Hi @Urdan ,

Which version of vopono are you running?

It's been set to use `nmcli connection reload` for a while, see https://github.com/jamesmcm/vopono/blob/c84734cc1bbaacd5870e27dccc5a49e8efa822f2/src/veth_pair.rs#L65

And could you please run `ip addr` to see the possible network interfaces as maybe `enp5s0` is not the right target in this case?

**Comment by Urdan** [comment]
Hi 

0.6.4

`$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a8:5e:45:51:12:61 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.2/24 brd 192.168.0.255 scope global noprefixroute enp5s0
       valid_lft forever preferred_lft forever
    inet6 fe80::23e:4153:f634:787c/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
`

Running Debian Buster KDE

Thank you.

**Comment by jamesmcm** [comment]
Thanks @Urdan ,

The `nmcli` issue is unrelated, it's a bug when it drops the wrapper, but this shouldn't happen usually.

The real issue is:

```
2021-02-05T21:30:11.666Z DEBUG vopono::util > nft add table inet vopono_nat
2021-02-05T21:30:11.668Z DEBUG vopono::util > nft add chain inet vopono_nat postrouting { type nat hook postrouting priority 100 ; } 
2021-02-05T21:30:11.671Z DEBUG vopono::util > nft add rule inet vopono_nat postrouting oifname enp5s0 ip saddr 10.200.1.0/24 counter masquerade 
Error: NAT is only supported for IPv4/IPv6 add rule inet vopono_nat postrouting oifname enp5s0 ip saddr 10.200.1.0/24 counter masquerade ^^^^^^^^^^
```

Could you try running it with the `--firewall iptables` flag please, and I'll try to look more in to the nftables issue later.

**Comment by Urdan** [comment]
I hope I've done this correctly. It asked me for a login :) 

`$ vopono -v exec --firewall iptables --custom /etc/openvpn/ovpn_tcp/us6116.nordvpn.com.tcp.ovpn --protocol openvpn "brave"
 2021-02-06T04:14:49.454Z DEBUG vopono::pulseaudio > Setting PULSE_SERVER to unix:/run/user/1000/pulse/native
 2021-02-06T04:14:49.454Z INFO  vopono::util       > Calling sudo for elevated privileges, current user will be used as default user
 2021-02-06T04:14:49.454Z DEBUG vopono::util       > Args: ["vopono", "-v", "exec", "--firewall", "iptables", "--custom", "/etc/openvpn/ovpn_tcp/us6116.nordvpn.com.tcp.ovpn", "--protocol", "openvpn", "brave"]
[sudo] password for xt88: 
 2021-02-06T04:14:57.654Z DEBUG vopono::pulseaudio > Setting PULSE_SERVER to unix:/run/user/1000/pulse/native
 2021-02-06T04:14:57.655Z DEBUG vopono::util       > Existing namespaces: ["vopono_custom_us61"]
 2021-02-06T04:14:57.655Z DEBUG vopono::util       > Removing dead namespace: vopono_custom_us61
 2021-02-06T04:14:57.655Z DEBUG vopono::util       > ip netns delete vopono_custom_us61
 2021-02-06T04:14:57.660Z DEBUG vopono::network_interface > ip addr
 2021-02-06T04:14:57.662Z DEBUG vopono::exec              > Interface: enp5s0
 2021-02-06T04:14:57.663Z DEBUG vopono::util              > Existing namespaces: []
 2021-02-06T04:14:57.663Z DEBUG vopono::util              > ip netns add vopono_custom_us61
 2021-02-06T04:14:57.669Z INFO  vopono::netns             > Created new network namespace: vopono_custom_us61
 2021-02-06T04:14:57.670Z DEBUG vopono::util              > Existing interfaces: 
 2021-02-06T04:14:57.671Z DEBUG vopono::util              > Assigned IPs: []
 2021-02-06T04:14:57.671Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip addr add 127.0.0.1/8 dev lo
 2021-02-06T04:14:57.674Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip link set lo up
 2021-02-06T04:14:57.677Z DEBUG vopono::veth_pair         > NetworkManager detected, adding custom_us61_d to unmanaged devices
 2021-02-06T04:14:57.677Z DEBUG vopono::util              > nmcli connection reload
 2021-02-06T04:14:57.708Z DEBUG vopono::util              > ip link add custom_us61_d type veth peer name custom_us61_s
 2021-02-06T04:14:57.711Z DEBUG vopono::util              > ip link set custom_us61_d up
 2021-02-06T04:14:57.715Z DEBUG vopono::util              > ip link set custom_us61_s netns vopono_custom_us61 up
 2021-02-06T04:14:57.749Z DEBUG vopono::util              > ip addr add 10.200.1.1/24 dev custom_us61_d
 2021-02-06T04:14:57.754Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip addr add 10.200.1.2/24 dev custom_us61_s
 2021-02-06T04:14:57.770Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip route add default via 10.200.1.1 dev custom_us61_s
 2021-02-06T04:14:57.775Z INFO  vopono::netns             > IP address of namespace as seen from host: 10.200.1.2
 2021-02-06T04:14:57.775Z INFO  vopono::netns             > IP address of host as seen from namespace: 10.200.1.1
 2021-02-06T04:14:57.775Z DEBUG vopono::util              > iptables -t nat -A POSTROUTING -s 10.200.1.0/24 -o enp5s0 -j MASQUERADE
 2021-02-06T04:14:57.855Z DEBUG vopono::util              > sysctl -q net.ipv4.ip_forward=1
 2021-02-06T04:14:57.858Z DEBUG vopono::dns_config        > Setting namespace vopono_custom_us61 DNS server to 8.8.8.8
 2021-02-06T04:14:57.860Z INFO  vopono::openvpn           > Launching OpenVPN...
 2021-02-06T04:14:57.860Z DEBUG vopono::openvpn           > Found remotes: [Remote { host: IPv4(89.187.187.35), port: 443, protocol: TCP }]
 2021-02-06T04:14:57.860Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 openvpn --config /etc/openvpn/ovpn_tcp/us6116.nordvpn.com.tcp.ovpn --machine-readable-output --log /etc/netns/vopono_custom_us61/openvpn.log
 2021-02-06T04:14:57.865Z DEBUG vopono::openvpn           > "1612584897.865191 1 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019\n"
 2021-02-06T04:14:57.865Z DEBUG vopono::openvpn           > "1612584897.865213 1 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10\n"
Enter Auth Username: mMoQ7zZAUAoxjPq8WRvEMSk7
Enter Auth Password: ************************
 2021-02-06T04:15:50.637Z DEBUG vopono::openvpn           > "1612584950.637705 40 WARNING: --ping should normally be used with --ping-restart or --ping-exit\n"
 2021-02-06T04:15:50.637Z DEBUG vopono::openvpn           > "1612584950.637738 1 NOTE: --fast-io is disabled since we are not using UDP\n"
 2021-02-06T04:15:50.638Z DEBUG vopono::openvpn           > "1612584950.638295 14000002 Outgoing Control Channel Authentication: Using 512 bit message hash \'SHA512\' for HMAC authentication\n"
 2021-02-06T04:15:50.638Z DEBUG vopono::openvpn           > "1612584950.638312 14000002 Incoming Control Channel Authentication: Using 512 bit message hash \'SHA512\' for HMAC authentication\n"
 2021-02-06T04:15:50.638Z DEBUG vopono::openvpn           > "1612584950.638461 1 TCP/UDP: Preserving recently used remote address: [AF_INET]89.187.187.35:443\n"
 2021-02-06T04:15:50.638Z DEBUG vopono::openvpn           > "1612584950.638497 2b000003 Socket Buffers: R=[131072->131072] S=[16384->16384]\n"
 2021-02-06T04:15:50.638Z DEBUG vopono::openvpn           > "1612584950.638506 1 Attempting to establish TCP connection with [AF_INET]89.187.187.35:443 [nonblock]\n"
 2021-02-06T04:15:51.638Z DEBUG vopono::openvpn           > "1612584951.638692 1 TCP connection established with [AF_INET]89.187.187.35:443\n"
 2021-02-06T04:15:51.638Z DEBUG vopono::openvpn           > "1612584951.638719 1 TCP_CLIENT link local: (not bound)\n"
 2021-02-06T04:15:51.638Z DEBUG vopono::openvpn           > "1612584951.638728 1 TCP_CLIENT link remote: [AF_INET]89.187.187.35:443\n"
 2021-02-06T04:15:51.796Z DEBUG vopono::openvpn           > "1612584951.796247 14000003 TLS: Initial packet from [AF_INET]89.187.187.35:443, sid=7ba8a035 8d6462f1\n"
 2021-02-06T04:15:51.796Z DEBUG vopono::openvpn           > "1612584951.796363 40 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465185 14000002 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465473 14000002 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465808 14000002 VERIFY KU OK\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465820 14000002 Validating certificate extended key usage\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465827 14000002 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465833 14000002 VERIFY EKU OK\n"
 2021-02-06T04:15:52.465Z DEBUG vopono::openvpn           > "1612584952.465838 14000002 VERIFY OK: depth=0, CN=us6116.nordvpn.com\n"
 2021-02-06T04:15:52.966Z DEBUG vopono::openvpn           > "1612584952.966676 14000002 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA\n"
 2021-02-06T04:15:52.966Z DEBUG vopono::openvpn           > "1612584952.966728 1 [us6116.nordvpn.com] Peer Connection Initiated with [AF_INET]89.187.187.35:443\n"
 2021-02-06T04:15:53.979Z DEBUG vopono::openvpn           > "1612584953.979758 22000003 SENT CONTROL [us6116.nordvpn.com]: \'PUSH_REQUEST\' (status=1)\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354814 22000003 PUSH: Received control message: \'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.0.3 255.255.255.0,peer-id 0,cipher AES-256-GCM\'\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > Found OpenVPN DNS response: 103.86.96.100
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > Set OpenVPN DNS to: V4(103.86.96.100)
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354949 22000003 OPTIONS IMPORT: timers and/or timeouts modified\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354958 22000003 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354964 22000003 OPTIONS IMPORT: compression parms modified\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354970 22000003 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354984 2b000003 Socket Buffers: R=[131072->425984] S=[87040->425984]\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354990 22000003 OPTIONS IMPORT: --ifconfig/up options modified\n"
 2021-02-06T04:15:54.354Z DEBUG vopono::openvpn           > "1612584954.354995 22000003 OPTIONS IMPORT: route options modified\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.354999 22000003 OPTIONS IMPORT: route-related options modified\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355004 22000003 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355009 22000003 OPTIONS IMPORT: peer-id set\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355014 22000003 OPTIONS IMPORT: adjusting link_mtu to 1659\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355018 22000003 OPTIONS IMPORT: data channel crypto options modified\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355025 14000002 Data Channel: using negotiated cipher \'AES-256-GCM\'\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355145 14000002 Outgoing Data Channel: Cipher \'AES-256-GCM\' initialized with 256 bit key\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355157 14000002 Incoming Data Channel: Cipher \'AES-256-GCM\' initialized with 256 bit key\n"
 2021-02-06T04:15:54.355Z DEBUG vopono::openvpn           > "1612584954.355301 3 ROUTE_GATEWAY 10.200.1.1/255.255.255.0 IFACE=custom_us61_s HWADDR=c2:8b:4c:df:78:62\n"
 2021-02-06T04:15:54.363Z DEBUG vopono::openvpn           > "1612584954.363376 1 TUN/TAP device tun0 opened\n"
 2021-02-06T04:15:54.363Z DEBUG vopono::openvpn           > "1612584954.363433 2b000003 TUN/TAP TX queue length set to 100\n"
 2021-02-06T04:15:54.363Z DEBUG vopono::openvpn           > "1612584954.363470 1 /sbin/ip link set dev tun0 up mtu 1500\n"
 2021-02-06T04:15:54.365Z DEBUG vopono::openvpn           > "1612584954.365383 1 /sbin/ip addr add dev tun0 10.7.0.3/24 broadcast 10.7.0.255\n"
 2021-02-06T04:15:54.366Z DEBUG vopono::openvpn           > "1612584954.366762 3 /sbin/ip route add 89.187.187.35/32 via"
 2021-02-06T04:15:54.366Z DEBUG vopono::openvpn           > " 10.200.1.1\n"
 2021-02-06T04:15:54.368Z DEBUG vopono::openvpn           > "1612584954.367998 3 /sbin/ip route add 0.0.0.0/1 via 10.7.0.1\n"
 2021-02-06T04:15:54.369Z DEBUG vopono::openvpn           > "1612584954.369512 3 /sbin/ip route add 128.0.0.0/1 via 10.7.0.1\n"
 2021-02-06T04:15:54.370Z DEBUG vopono::openvpn           > "1612584954.370943 1 Initialization Sequence Completed\n"
 2021-02-06T04:15:54.370Z DEBUG vopono::openvpn           > Setting OpenVPN killswitch....
 2021-02-06T04:15:54.370Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -P INPUT DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.373Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -P FORWARD DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.375Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -P OUTPUT DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.376Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.381Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A INPUT -i lo -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.384Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A INPUT -i tun+ -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.388Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A OUTPUT -o lo -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.390Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A OUTPUT -d 8.8.8.8 -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.393Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.403Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A OUTPUT -o tun+ -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.405Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 iptables -A OUTPUT -j REJECT --reject-with icmp-net-unreachable
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.413Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -P INPUT DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.415Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -P FORWARD DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.421Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -P OUTPUT DROP
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.422Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.424Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A INPUT -i lo -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.425Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A INPUT -i tun+ -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.427Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A OUTPUT -o lo -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.429Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A OUTPUT -o tun+ -j ACCEPT
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-02-06T04:15:54.432Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 ip6tables -A OUTPUT -j REJECT --reject-with icmp-net-unreachable
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
ip6tables v1.8.2 (nf_tables): unknown reject type "icmp-net-unreachable"
Try `ip6tables -h' or 'ip6tables --help' for more information.
 2021-02-06T04:15:54.439Z DEBUG vopono::exec              > Checking that OpenVPN is running in namespace: vopono_custom_us61
 2021-02-06T04:15:54.490Z DEBUG vopono::dns_config        > Setting namespace vopono_custom_us61 DNS server to 103.86.96.100
 2021-02-06T04:15:54.490Z DEBUG vopono::netns             > Writing lockfile: /home/xt88/.config/vopono/locks/vopono_custom_us61
 2021-02-06T04:15:54.490Z DEBUG vopono::netns             > Lockfile written: /home/xt88/.config/vopono/locks/vopono_custom_us61/11448
 2021-02-06T04:15:54.525Z DEBUG vopono::netns             > ip netns exec vopono_custom_us61 sudo -Eu xt88 brave
 2021-02-06T04:15:54.526Z INFO  vopono::exec              > Application brave launched in network namespace vopono_custom_us61 with pid 11588
Bind /etc/netns/vopono_custom_us61/openvpn.log -> /etc/openvpn.log failed: No such file or directory
sudo: brave: command not found
 2021-02-06T04:15:54.565Z DEBUG vopono::openvpn           > Killed OpenVPN (pid: 11503)
 2021-02-06T04:15:54.565Z DEBUG vopono::util              > ip link delete custom_us61_d
 2021-02-06T04:15:54.608Z DEBUG vopono::util              > nmcli general reload
Error: argument 'reload' not understood. Try passing --help instead.
thread 'main' panicked at 'Failed to reload NetworkManager configuration: Command failed: nmcli general reload', src/veth_pair.rs:127:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2021-02-06T04:15:54.620Z DEBUG vopono::util              > iptables -t nat -D POSTROUTING -s 10.200.1.0/24 -o enp5s0 -j MASQUERADE
$
`

**Comment by jamesmcm** [comment]
@Urdan the error above is:

>sudo: brave: command not found

Try using `brave-browser` instead of `brave`.

**Comment by milahu** [comment]
> OpenVPN only:
>
> ExpressVPN

[expressvpn.com](https://www.expressvpn.com/) provides 2 protocols: OpenVPN, Lightway.

[Lightway is similar to Wireguard](https://www.allthingssecured.com/vpn/faq/lightway-vs-wireguard-vs-openvpn/).
[lightway-core](https://github.com/expressvpn/lightway-core) is open-source.
there is an open-source client [lightway-laser](https://github.com/expressvpn/lightway-laser) and a closed-source client [expressvpn-vpn-linux](https://www.expressvpn.com/vpn-software/vpn-linux).

in [my ranking](https://github.com/milahu/fully-open-source-wireguard-vpn-providers), expressvpn.com has a low rank, because expressvpn.com is owned by Kape Technologies, which has connections to Israel military (Unit 8200, similar to NSA), which is owner of multiple VPN providers: CyberGhost VPN, Zenmate VPN, Private Internet Access, ExpressVPN
